# Application Info
application.name: ReNameo
application.version: 1.0.0

# Web services (API keys are set in profile.properties, see profile.properties.example)
url.data: https://app.filebot.net/data
apikey.fanart.tv:
apikey.thetvdb:
apikey.themoviedb:
apikey.omdb:
apikey.acoustid:
apikey.anidb:
apikey.opensubtitles:

# Script Base URL
github.stable: https://app.filebot.net/scripts/m1.jar.xz
github.master: https://raw.githubusercontent.com/filebot/scripts/master/

# Update Descriptor (no update server for now)
update.url:

# Store (not applicable)
link.mas:
link.mws:

# Tutorials
link.app.help:

# Help (no external support endpoints yet)
link.intro:
link.forums:
link.twitter:
link.facebook:
link.faq:
link.bugs:
link.channel:
link.help:
link.help.mas:
link.help.mws:
link.help.manpage:
link.help.synology:

# Images
link.image.logo:

# Build
main.class: net.renameo.Main
jre.version: 10

# Minimum System Version
jvm.version: 10
mac.version: 10.10

# Package Information
package.name: renameo
package.identifier: net.renameo.app
package.developer:
package.maintainer:
package.company:
package.project: ReNameo
package.synopsis: The smart way to organize and rename your movies and TV shows
package.description: ReNameo helps you organize and rename all your Movies, TV Shows and Anime, and fetch subtitles and artwork. It's smart and just works.
package.tags: Mass Renamer, Rename TV shows, Rename movies, Organize media files, Fetch Subtitles, Check SFV files, Plex Media Server, Kodi Media Center, TheTVDB, TheMovieDB, OpenSubtitles
package.homepage:

# Distribution-specific Package Information
microsoft.application.name: ReNameo.App
microsoft.application.publisher:

# Platform-specific Package Information
mac.application.category: public.app-category.utilities
deb.application.categories: AudioVideo;Video;Utility;FileTools;
deb.application.mimetype: inode/directory;video/*;audio/*;text/*;application/*;
deb.application.class: net-filebot-Main

# Commands
deb.application.action.import: renameo -script fn:amc --output "$HOME/Media" --action duplicate -non-strict --log-file "$HOME/Media/amc.log" --def excludeList="$HOME/Media/amc.excludes" unsorted=y music=y artwork=y

# Default Java Options
java.application.options: -Dunixfs=false -DuseExtendedFileAttributes=true -DuseCreationDate=false -Djava.net.useSystemProxies=true -Djna.nosys=true -Djna.nounpack=true --illegal-access=permit --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.function=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio.file=ALL-UNNAMED --add-opens=java.base/java.nio.file.attribute=ALL-UNNAMED --add-opens=java.base/java.nio.channels=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.logging/java.util.logging=ALL-UNNAMED
