<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<project name="renameo" default="fatjar" xmlns:if="ant:if" xmlns:unless="ant:unless" xmlns:ivy="antlib:org.apache.ivy.ant">

	<!-- define source dirs -->
	<property name="dir.source" location="${basedir}/source" />
	<property name="dir.build" location="${basedir}/build" />
	<property name="dir.dist" location="${basedir}/dist" />
	<property name="dir.lib" location="${basedir}/lib" />

	<!-- import property files -->
	<property file="${basedir}/profile.properties" />
	<property file="${basedir}/app.properties" />

	<property name="release" value="${application.name}_${application.version}" />

	<!-- define output paths -->
	<property name="dir.cache" location="${basedir}/cache" />
	<property name="dir.release" location="${basedir}/release/${release}" />
	<property name="path.fatjar" location="${dir.dist}/${release}.jar" />


	<!-- timestamp variables -->
	<tstamp prefix="tstamp">
		<format property="date" pattern="yyyy-MM-dd" />
		<format property="year" pattern="yyyy" />
	</tstamp>


	<!-- copy and replace ant variables macro -->
	<macrodef name="copy-replace">
		<attribute name="todir" />
		<element name="filesets" implicit="yes" />
		<sequential>
			<copy todir="@{todir}" encoding="utf-8" overwrite="yes" verbose="yes">
				<filesets />
				<filterset begintoken="@{" endtoken="}">
					<propertyset>
						<propertyref builtin="all" />
					</propertyset>
				</filterset>
			</copy>
		</sequential>
	</macrodef>


	<!-- sign with gpg macro -->


	<!-- deploy release artifacts -->


	<target name="resolve" description="Retrieve dependencies with Apache Ivy">
		<delete dir="${dir.lib}/ivy" />
		<ivy:retrieve pattern="${dir.lib}/ivy/[type]/[artifact].[ext]" />

		<antcall target="resolve-import-native">
			<param name="arch" value="mac-x86_64" />
			<param name="arch.jna" value="darwin" />
			<param name="arch.7zj" value="Mac-x86_64" />
		</antcall>
	</target>


	<target name="resolve-import-native">
		<unzip src="${dir.lib}/ivy/jar/jna.jar" dest="${dir.lib}/native/${arch}" overwrite="yes">
			<patternset>
				<include name="**/${arch.jna}/*.dll" />
				<include name="**/${arch.jna}/*.so" />
				<include name="**/${arch.jna}/*.jnilib" />
			</patternset>
			<chainedmapper>
				<flattenmapper />
				<compositemapper>
					<globmapper from="*.jnilib" to="*.dylib" />
					<identitymapper />
				</compositemapper>
			</chainedmapper>
		</unzip>
		<unzip src="${dir.lib}/ivy/jar/sevenzipjbinding-all-platforms.jar" dest="${dir.lib}/native/${arch}" overwrite="yes">
			<patternset>
				<include name="**/${arch.7zj}/*.dll" />
				<include name="**/${arch.7zj}/*.so" />
				<include name="**/${arch.7zj}/*.dylib" />
			</patternset>
			<chainedmapper>
				<flattenmapper />
				<compositemapper>
					<globmapper from="lib*.dll" to="*.dll" />
					<identitymapper />
				</compositemapper>
			</chainedmapper>
		</unzip>
	</target>


	<target name="jar" depends="build">
		<jar destfile="${dir.dist}/lib/renameo.jar" compress="no">
			<!-- only the compiled application: build/ also holds test classes and packaging input -->
			<fileset dir="${dir.build}">
				<include name="net/**" />
				<include name="META-INF/**" />
				<include name="*.xml" />
			</fileset>
			<manifest>
				<attribute name="Build-Date" value="${tstamp.date}" />
				<attribute name="Build-Revision" value="${revision}" />
			</manifest>
		</jar>
	</target>


	<target name="fatjar" depends="jar" description="Build executable jar">
		<jar destfile="${path.fatjar}" filesetmanifest="merge" duplicate="fail" compress="yes" level="9">
			<!-- Manifest for fatjar so its executable-->
			<manifest>
				<attribute name="Main-Class" value="net.renameo.Main"/>
			</manifest>

			<!-- include main jar -->
			<zipfileset src="${dir.dist}/lib/renameo.jar" />

			<!-- include core libraries -->
			<zipfileset src="${dir.dist}/lib/args4j.jar">
				<include name="org/kohsuke/args4j/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/ehcache.jar">
				<include name="META-INF/services/**" />
				<include name="net/sf/ehcache/**" />
				<include name="org/terracotta/**" />
				<include name="ehcache-failsafe.xml" />
				<include name="build-info.properties" />
			</zipfileset>

			<!-- include UI libraries -->
			<zipfileset src="${dir.dist}/lib/miglayout-core.jar">
				<include name="net/miginfocom/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/miglayout-swing.jar">
				<include name="net/miginfocom/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/glazedlists_java16.jar">
				<include name="ca/odell/glazedlists/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/rsyntaxtextarea.jar">
				<include name="org/fife/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/lanterna.jar">
				<include name="com/googlecode/lanterna/**" />
				<include name="**/*.properties" />
			</zipfileset>

			<!-- include IO libraries -->
			<zipfileset src="${dir.dist}/lib/xz.jar">
				<include name="org/tukaani/xz/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/json-io.jar">
				<include name="com/cedarsoftware/util/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/sevenzipjbinding.jar">
				<include name="net/sf/sevenzipjbinding/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/commons-io.jar">
				<include name="org/apache/commons/io/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/commons-vfs2.jar">
				<include name="org/apache/commons/vfs2/**" />
			</zipfileset>


			<zipfileset src="${dir.dist}/lib/junrar.jar">
				<include name="com/github/junrar/**" />
			</zipfileset>

			<!-- include native libraries -->
			<zipfileset src="${dir.dist}/lib/ObjCBridge.jar">
				<include name="ca/weblite/**" />
				<include name="com/sun/jna/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/jna.jar">
				<include name="com/sun/jna/**" />

				<!-- exclude native libraries except the macOS dispatch library (arm64 + x86_64), which JNA extracts at runtime -->
				<exclude name="**/*.a" />
				<exclude name="**/*.so" />
				<exclude name="**/*.dll" />
				<exclude name="**/*.dylib" />
			</zipfileset>
			<!-- JNA dispatch libraries for Linux and Windows (Docker, NAS, desktop packages) -->
			<zipfileset src="${dir.dist}/lib/jna.jar">
				<include name="com/sun/jna/linux-x86-64/*.so" />
				<include name="com/sun/jna/linux-aarch64/*.so" />
				<include name="com/sun/jna/win32-x86-64/*.dll" />
				<include name="com/sun/jna/win32-aarch64/*.dll" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/jna-platform.jar">
				<include name="com/sun/jna/platform/**" />
			</zipfileset>

			<!-- include extra libraries -->
			<zipfileset src="${dir.dist}/lib/guava.jar">
				<include name="com/google/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/failureaccess.jar">
				<include name="com/google/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/streamex.jar">
				<include name="one/util/streamex/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/icu4j.jar">
				<include name="com/ibm/icu/**" />

				<!-- only transliteration (which needs the word break data for Thai, Lao, Khmer, Burmese) and charset detection are used: leave out collation, currency, language, region, time zone, unit and number spellout data -->
				<exclude name="com/ibm/icu/impl/data/icud*/coll/**" />
				<exclude name="com/ibm/icu/impl/data/icud*/curr/**" />
				<exclude name="com/ibm/icu/impl/data/icud*/lang/**" />
				<exclude name="com/ibm/icu/impl/data/icud*/region/**" />
				<exclude name="com/ibm/icu/impl/data/icud*/zone/**" />
				<exclude name="com/ibm/icu/impl/data/icud*/unit/**" />
				<exclude name="com/ibm/icu/impl/data/icud*/rbnf/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/simmetrics.jar">
				<include name="uk/ac/shef/wit/simmetrics/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/language-detector.jar">
				<include name="be/frma/langguess/**" />
				<include name="com/cybozu/labs/langdetect/**" />
				<include name="com/optimaize/langdetect/**" />
				<include name="languages/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/metadata-extractor.jar">
				<include name="com/drew/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/xmpcore.jar">
				<include name="com/adobe/xmp/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/jacksum.jar">
				<include name="jonelo/jacksum/adapt/**" />
				<include name="jonelo/jacksum/algorithm/**" />
				<include name="jonelo/sugar/util/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/commons-logging.jar">
				<include name="org/apache/commons/logging/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/slf4j-api.jar">
				<include name="org/slf4j/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/slf4j-jdk14.jar">
				<include name="org/slf4j/**" />
			</zipfileset>

			<!-- include Groovy libraries (Groovy 4 modules; their extension module descriptors are merged in source/META-INF/groovy) -->
			<zipfileset src="${dir.dist}/lib/groovy.jar">
				<include name="groovy/**" />
				<include name="groovyjarjar*/**" />
				<include name="org/codehaus/groovy/**" />
				<include name="org/apache/groovy/**" />
				<include name="META-INF/dgminfo" />
				<include name="META-INF/groovy-release-info.properties" />
				<include name="META-INF/groovy/org.codehaus.groovy.source.Extensions" />
				<include name="META-INF/services/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/groovy-jsr223.jar">
				<include name="org/codehaus/groovy/jsr223/**" />
				<include name="META-INF/services/javax.script.ScriptEngineFactory" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/groovy-json.jar">
				<include name="groovy/json/**" />
				<include name="org/apache/groovy/json/**" />
				<include name="META-INF/services/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/groovy-xml.jar">
				<include name="groovy/xml/**" />
				<include name="groovy/util/**" />
				<include name="org/apache/groovy/xml/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/groovy-dateutil.jar">
				<include name="org/apache/groovy/dateutil/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/groovy-datetime.jar">
				<include name="org/apache/groovy/datetime/**" />
			</zipfileset>
			<zipfileset src="${dir.dist}/lib/groovy-nio.jar">
				<include name="org/apache/groovy/nio/**" />
			</zipfileset>


			<!-- libraries used in external scripts -->
			<zipfileset src="${dir.dist}/lib/jsoup.jar">
				<include name="org/jsoup/**" />
			</zipfileset>

		</jar>
	</target>


	<target name="build" depends="revision">
		<!-- copy dependencies (from scratch, so a removed library can't linger on the classpath) -->
		<delete dir="${dir.dist}/lib" />
		<copy todir="${dir.dist}/lib" flatten="yes" verbose="yes">
			<fileset dir="${dir.lib}/ivy/jar">
				<include name="ehcache.jar" />
				<include name="miglayout-core.jar" />
				<include name="miglayout-swing.jar" />
				<include name="glazedlists_java16.jar" />
				<include name="rsyntaxtextarea.jar" />
				<include name="lanterna.jar" />
				<include name="xz.jar" />
				<include name="sevenzipjbinding.jar" />
				<include name="commons-io.jar" />
				<include name="commons-vfs2.jar" />
				<include name="junrar.jar" />
				<include name="jna.jar" />
				<include name="jna-platform.jar" />
				<include name="streamex.jar" />
				<include name="icu4j.jar" />
				<include name="language-detector.jar" />
				<include name="metadata-extractor.jar" />
				<include name="xmpcore.jar" />
				<include name="commons-logging.jar" />
				<include name="slf4j-api.jar" />
				<include name="slf4j-jdk14.jar" />
				<include name="groovy.jar" />
				<include name="groovy-jsr223.jar" />
				<include name="groovy-json.jar" />
				<include name="groovy-xml.jar" />
				<include name="groovy-dateutil.jar" />
				<include name="groovy-datetime.jar" />
				<include name="groovy-nio.jar" />
				<include name="jsoup.jar" />
			</fileset>
			<fileset dir="${dir.lib}/ivy/bundle">
				<include name="xmpcore.jar" />
				<include name="args4j.jar" />
				<include name="json-io.jar" />
				<include name="guava.jar" />
				<include name="failureaccess.jar" />
			</fileset>
			<fileset dir="${dir.lib}/jars">
				<include name="ObjCBridge.jar" />
				<include name="simmetrics.jar" />
				<include name="jacksum.jar" />
			</fileset>
		</copy>

		<!-- compile -->
		<javac srcdir="${dir.source}" destdir="${dir.build}" release="${jvm.version}" encoding="utf-8" debug="yes" debuglevel="lines,vars,source" includeAntRuntime="no">
			<classpath>
				<fileset dir="${dir.dist}/lib" />
			</classpath>
		</javac>

		<!-- copy property files -->
		<copy-replace todir="${dir.build}">
			<fileset dir="${dir.source}" includes="**/*.properties" />
		</copy-replace>

		<!-- copy resources -->
		<copy todir="${dir.build}">
			<fileset dir="${dir.source}">
				<exclude name="**/*.java" />
				<exclude name="**/*.properties" />
			</fileset>
		</copy>

		<!-- offline indexes and release data -->
		<delete dir="${dir.build}/net/renameo/data" />
		<copy todir="${dir.build}/net/renameo/data">
			<fileset dir="${basedir}/data" includes="*.txt.xz" />
		</copy>
	</target>


	<target name="clean" description="Delete build folders">
		<delete dir="${dir.dist}" />
		<delete dir="${dir.build}" />
	</target>


	<target name="revision" depends="init">
		<!-- commit count of the current branch, 1 outside of a git checkout -->
		<exec executable="git" outputproperty="git.revision" errorproperty="git.error" resultproperty="git.result" failonerror="false" failifexecutionfails="false">
			<arg line="rev-list --count HEAD" />
		</exec>
		<condition property="revision" value="${git.revision}" else="1">
			<equals arg1="${git.result}" arg2="0" />
		</condition>
		<echo>Revision: ${revision}</echo>
	</target>


	<target name="init">
		<mkdir dir="${dir.build}" />
		<mkdir dir="${dir.dist}" />
		<mkdir dir="${dir.release}" />
		<mkdir dir="${dir.cache}" />

		<path id="lib.classpath">
			<fileset dir="${dir.lib}" includes="**/*.jar" excludes="**/*-jdk14.jar" />
		</path>
	</target>


</project>